name: gcp_list
services:

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: default

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URI: "postgresql://admin:12345@localhost:5432/default?sslmode=disable"
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - ./:/app
      - /app/node_modules
